services:
  postgre:
   image: postgres:${POSTGRES_TAG}
   restart: always
   container_name: postgresdb
   ports:
    - 5432:5432
   networks:
    - kube_news_net
   volumes:
    - postgre_docker_vol:/var/lib/postgresql/data
   environment:
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_DB: ${POSTGRES_DB}

  kube_news:
    image: kubedevio/kube-news:${KUBE_NEWS_TAG:-latest}
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - kube_news_net
    depends_on:
      - postgre
    environment:
      DB_HOST: postgre
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USERNAME: ${POSTGRES_USER}
      DB_DATABASE: ${POSTGRES_DB}      

volumes:
  postgre_docker_vol:

networks:
  kube_news_net:
    driver: bridge